### ISSUE TITLE
Installation works with Python 3.9.5 exclusively

### ISSUE THREAD

**Issue by johentsch** [apmcleod/harmonic-inference#71]
At first I tried to install in a Python 3.10 environment (which is also what you get when creating the conda environment with `python=3`) but installation failed while a C subroutine was compiling numpy. Then I used an environment created with `python=3.9` which lead to

```
INFO: pip is looking at multiple versions of harmonic-inference[dev] to determine which version is compatible with other requirements. This could take a while.
ERROR: Package 'harmonic-inference' requires a different Python: 3.9.16 not in '==3.9.5'
```

In a new environment created with `python=3.9.5` the installation worked.

**Comment by apmcleod** [comment]
3.10 will be supported in the next major release, which will fix a lot of these version issues. For now, pinning to 3.9.5 should be done manually with conda as you wrote.

**Comment by johentsch** [comment]
Thanks, can confirm that everything works for me when using the `output` branch.

**Comment by johentsch** [comment]
Actually, `ms3>=1.0.0` requires Python 3.10. Therefore, since the merging #73 into `output`, there is a dependency conflict on that branch.

**Comment by apmcleod** [comment]
I just updated the setup file to require python >= 3.10. I confirmed that I could create an environment with the current setup.cfg in the output branch.
