### ISSUE TITLE
annotate.py does not run with newer versions of torchmetrics and setuptools

### ISSUE THREAD

**Issue by johentsch** [apmcleod/harmonic-inference#72]
Tried `python annotate.py -h` after doing the indicated installation in a `python=3.9.5` environment which left me with `torch==1.9.0` and `torchmetrics==0.11`.  The result was

```
ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' (.../lib/python3.9/site-packages/torchmetrics/utilities/data.py)
```

Downgrading to `torchmetrics==0.7` solved the issue as per https://github.com/pesser/stable-diffusion/issues/13

Then the same command yielded

```
AttributeError: module 'distutils' has no attribute 'version'
```

which I managed to solve by installing `setuptools==59.5.0` as per https://stackoverflow.com/questions/74684612/attributeerror-module-distutils-has-no-attribute-version

**Comment by apmcleod** [comment]
Thank you for finding this! I guess torchmetrics removed a function, and its version wasn't pinned correctly within pytorch_lightning or torch (I don't have torchmetrics as an explicit dependency). Newer versions will solve this, and that is planned to be supported in the next major release as well.

**Comment by johentsch** [comment]
Thanks, can confirm that everything works for me when using the `output` branch.
