### ISSUE TITLE
Loading forces fails with `AttributeError: 'NoneType' object has no attribute 'get_score_piece'`

### ISSUE THREAD

**Issue by johentsch** [apmcleod/harmonic-inference#77]
In order to reproduce this bug, checkout #76 to fix an `ms3` bug in the discovery of scores containing forces.

The error message occurs for this [corpus_data.zip](https://github.com/apmcleod/harmonic-inference/files/11375152/corpus_data.zip) when executing `python annotate.py --label-type dcml --checkpoint checkpoints-beat-best -l annotate.log -i ~/corpus_data -o ~/corpus_data --forces ~/corpus_data/MS3`.

```python-traceback
Getting harmony for pieces:   0%|                                                                       | 0/5 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "~/harmonic-inference/annotate.py", line 378, in <module>
    annotate(
  File "~/harmonic-inference/annotate.py", line 185, in annotate
    state, estimated_piece = model.get_harmony(piece, **forces_dict)
  File "~/harmonic-inference/harmonic_inference/models/joint_model.py", line 789, in get_harmony
    self.kppm_post_processing(state)
  File "~/harmonic-inference/harmonic_inference/models/joint_model.py", line 1605, in kppm_post_processing
    piece = state.get_score_piece(
AttributeError: 'NoneType' object has no attribute 'get_score_piece'
```

**Comment by apmcleod** [comment]
Can confirm that I can reproduce this error. Will look at it Friday or (more likely) Monday. Let me know if that's too late for you, and I'll see what I can do sooner.

PS. Nice issue title.
*Edit* Nice *PR* title

**Comment by apmcleod** [comment]
This one will take a bit longer to debug. My Monday estimate is probably most likely.

**Comment by johentsch** [comment]
> Let me know if that's too late for you, and I'll see what I can do sooner.

No worries, I'm not working on a schedule. Thanks for looking into this, looking forward to trying it out!

**Comment by apmcleod** [comment]
I found 2 missing indexes and fixed them. This seems to work now after the most recent 2 commits on the output branch. Please close if you agree :)

**Comment by johentsch** [comment]
Yep it's working, thanks.
